# Generated by Django 4.2 on 2025-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('Завод', 'Завод'), ('Розничная сеть', 'Розничная сеть'), ('Индивидуальный предприниматель', 'Индивидуальный предприниматель')], default=1, max_length=150, verbose_name='Тип компании'),
            preserve_default=False,
        ),
    ]
